name: Build

on:
  push:
    branches: [master, main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [master, main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Emby.Plugin.Template.sln

      - name: Build
        run: dotnet build Emby.Plugin.Template.sln --no-restore -c Release
